name: dslink_mongodb_controller
description: MongoDB DSLink.
version: 0.0.1

environment:
  sdk: '>=1.17.0 <2.0.0'
dependencies:
  mongo_dart:
    git: https://github.com/IOT-DSA/mongo_dart.git
  pool: any
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart
dev_dependencies:
  test: '>= 0.12.0 < 0.12.15'
  mockito: '<= 2.0.0'
