name: dslink_dslink_mongodb_management
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=1.17.1 <2.0.0'
dependencies:
  mongo_dart: '^0.2.8'
  pool: any
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart
dev_dependencies:
  test: '>= 0.12.0 < 0.12.15'
  mockito: '<= 2.0.0'
